### PR TITLE
Release v1.0.0

### PR DESCRIPTION
**Pull request by wongma7**
**Is this a bug fix or adding new feature?** new

**What is this PR about? / Why do we need it?** There are lots of changes over the last few months to release.

We're going GA.

As part of that, a big change merged today is that encryption in transit will be enabled by default. It should be backwards compatible. Regardless, the bump to 1.0.0 + the CHANGELOG should be sufficient signal for users about it.

Also, the new access points syntax introduced recently.

Major bug fixes related to TLS mounts + driver restarts/upgrades are included in the update to efs-utils.

To generate the CHANGELOG, I ran 
```
./hack/release --repo kubernetes-sigs/aws-efs-csi-driver --github-user wongma7 --github-token <SNIP> note --since v0.3.0
```
from https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/hack/release then pruned some lines.

TODO:

- [x] Prune the release notes even further. Many of the changes are not notable, for example changes to tests. I already pruned the following for being net-zero changes:
```
* Remove hostNetwork from daemonset yamls ([#159](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/159), [@wongma7](https://github.com/wongma7))
* Doc: Access Points: Require separate file systems ([#168](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/168), [@2uasimojo](https://github.com/2uasimojo))
* Persisted private key genereated by efs-util to host ([#179](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/179), [@jqmichael](https://github.com/jqmichael))
* Add hostNetwork: true to daemonset yamls ([#188](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/188), [@wongma7](https://github.com/wongma7))
* Revert "Persisted private key genereated by efs-util to host" ([#196](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/196), [@wongma7](https://github.com/wongma7))
```
Pruned in round 2:
```
* Post release update ([#140](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/140), [@leakingtapan](https://github.com/leakingtapan))
* Move EFS tests into e2e.go so that they can be imported from elsewhere ([#148](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/148), [@wongma7](https://github.com/wongma7))
* Add myself to owners ([#157](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/157), [@nckturner](https://github.com/nckturner))
* Enable e2e testing on EKS, parallelism, and make optional EFS creation/driver deployment ([#160](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/160), [@wongma7](https://github.com/wongma7))
* Bump stable overlay to 0.3.0 ([#161](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/161), [@wongma7](https://github.com/wongma7))
* Update stable overlay to use public images ([#162](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/162), [@leakingtapan](https://github.com/leakingtapan))
* Added client source for business tracking purpose ([#165](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/165), [@jqmichael](https://github.com/jqmichael))
* Remove dockerfile for dev ([#170](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/170), [@leakingtapan](https://github.com/leakingtapan))
* Correcting typo in access points example ([#171](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/171), [@lammichael](https://github.com/lammichael))
* Add e2e test for mounting different paths on same volume on same node ([#173](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/173), [@wongma7](https://github.com/wongma7))
* DRY TestNodePublishVolume ([#186](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/186), [@2uasimojo](https://github.com/2uasimojo))
* Add test for restarting/deleting driver pod affecting existing mount read/write ([#187](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/187), [@wongma7](https://github.com/wongma7))
* Fix TestNodeUnpublishVolume ([#189](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/189), [@2uasimojo](https://github.com/2uasimojo))
* Refactor and extend node tests ([#190](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/190), [@2uasimojo](https://github.com/2uasimojo))
* Update dev overlay to correctly set imagePullPolicy ([#195](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/195), [@ossareh](https://github.com/ossareh))
* Move the index file to gh-pages branch ([#199](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/199), [@leakingtapan](https://github.com/leakingtapan))
```
TODO IMMEDIATELY AFTER THIS MERGES: 
- [ ] Push a release-1.0 branch and v1.0.0 tag
- [ ] Verify GitHub actions happened: release was created, images built and pushed.
- [ ] Create a post v1.0.0 release PR to update the changelog with the commit SHA using:
```
./hack/release --repo kubernetes-sigs/aws-efs-csi-driver --github-user wongma7 --github-token <WHOOPS I REVOKED IT> sha --version v1.0.0
```

- [ ] Update the ECR overlay too (there is a delay between when images are available in docker hub vs ECR)

**What testing is done?** N/A
~~TODO: test install works with the changed YAMLs/helm.~~

### CODE REVIEW

**Comment by wongma7** [comment]
@leakingtapan FYI, this is the 1.0.0 release PR. I used your scripts from EBS repo!

**Comment by 2uasimojo** [comment]
:eyes:

**Comment by wongma7** [comment]
/hold

ready for review, but I want to unhold it myself when I'm ready

**Pull request merged**
