### PR TITLE
Remove hostNetwork from manifests

### PR DESCRIPTION
**Pull request by groodt**
Fixes https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/736

After https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/681 was merged, I deployed it to my clusters and tested the removal of `hostNetwork`. Everything works correctly!

This PR makes the necessary changes to the Helm charts and kustomize YAML.

### CODE REVIEW

**Comment by groodt** [comment]
Ping

**Comment by groodt** [comment]
PIng

**Comment by groodt** [comment]
cc @wongma7

**Comment by groodt** [comment]
Any chance you could take a look please @Ashley-wenyizha ?

**Comment by jingxu97** [comment]
do we still want this chage?

**Comment by groodt** [comment]
> do we still want this chage?

Yes, I believe we should make the defaults more secure by removing hostNetwork from the manifests.

**Comment by Ashley-wenyizha** [comment]
We have merged in this change together with https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1088/files

Closing

Thanks Greg!

**Pull request closed without merging**
