### PR TITLE
Conditionally added AWS_STS_REGIONAL_ENDPOINTS flag

### PR DESCRIPTION
**Pull request by holmesb**
to controller's efs-plugin container. Is needed to create persistent volumes on private EKS clusters. Without this, dynamic pv creation errors: "Failed to fetch File System info: Describe File System failed"

**Is this a bug fix or adding new feature?**
new feature (adds support for private eks clusters)

### CODE REVIEW

**Comment by holmesb** [comment]
Is anyone able to review this?  Probably fixes issues #555 & #499

**Comment by holmesb** [comment]
Fixed merge conflict @wongma7

**Comment by wongma7** [comment]
/lgtm
/approve

apologies for super long review time, I did another merge/rebase via github ui

**Pull request merged**
