### PR TITLE
chore: update go and deps to address CVEs

### PR DESCRIPTION
**Pull request by andrewjamesbrown**
**Is this a bug fix or adding new feature?**
Dependency updates.  Fixes https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/1503

**What is this PR about? / Why do we need it?**
- go 1.22.5 has a number of outstanding CVEs, update to 1.22.9 to pick up fixes
- go.sum was not updated as part of https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1475, so `grype` is still reporting it as part of the release
- updates as part of `go mod tidy`

**What testing is done?**

### CODE REVIEW

**Comment by andrewjamesbrown** [comment]
@mskanth972 should be good to go now (tests were passing before I squashed into one commit)
Thanks for the quick response!

**Comment by seanzatzdev-amazon** [comment]
Thanks for the contribution! I have approved your changes/will merge soon

**Pull request merged**
