### PR TITLE
update kube dependencies to 1.22.1 and aws-sdk to 1.40.29

### PR DESCRIPTION
**Pull request by Ashtonian**
**Is this a bug fix or adding new feature?**
Feature 

**What is this PR about? / Why do we need it?**
update aws sdk to support new az endpoints and other things

**What testing is done?** 
not enough, I am unable to run e2e, please help

Not sure vendoring is right, please verify. Only made a few code changes to accommodate new kube internal packages.

### CODE REVIEW

**Comment by Ashtonian** [comment]
This looks like it passed can it be merged ?

**Comment by wongma7** [comment]
sorry, I missed this and https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/553/files merged first despite being submitted after. Do you mind rebasing by just running go mod tidy and go mod vendor again? ty

**Comment by Ashtonian** [comment]
@wongma7 done.

**Comment by wongma7** [comment]
/lgtm
/approve

thanks! much appreciated.

**Pull request merged**
