### PR TITLE
feat(pdb): add optional podDisruptionBudget to controller deployment

### PR DESCRIPTION
**Pull request by starlightromero**
**Is this a bug fix or adding new feature?**
Feature

**What is this PR about? / Why do we need it?**
Add optional podDisruptionBudget to controller deployment

**What testing is done?** 
Template locally podDistruptionBudget with and without values

### CODE REVIEW

**Comment by starlightromero** [comment]
@d-nishi @leakingtapan 
Can I please receive your review on the PR?

**Comment by starlightromero** [comment]
@mskanth972 Can I please receive your review?

**Comment by rgarrigue** [comment]
I'm interested in this one. A pdb would let cluster-autoscaler do its job

> cluster-autoscaler-7dc4bc9569-d4szh cluster-autoscaler I1130 10:48:52.271557       1 cluster.go:164] node ip-10-3-11-162.eu-north-1.compute.internal cannot be removed: non-daemonset, non-mirrored, non-pdb-assigned kube-system pod present: efs-csi-controller-79fdf99b86-zwg2t

**Comment by sstarcher** [comment]
Can we get this reopened and tested.  It's a very simple change that everyone should be using.

**Review by sstarcher — COMMENTED** [review]
these changes look good

**Pull request closed without merging**
