### PR TITLE
templatize namespace & priorityClassName

### PR DESCRIPTION
**Pull request by wiesa1**
**Is this a bug fix or adding new feature?**
feature

**What is this PR about? / Why do we need it?**
Templatized _namespace_ and _priorityClassName_ in daemonset.yaml

Just to provide an option to deploy the driver in a different namespace and the option to specify a custom priority class

**What testing is done?**
installed modified helm chart locally

### CODE REVIEW

**Comment by wiesa1** [comment]
I signed the CLA

**Comment by wongma7** [comment]
/lgtm
/approve

I'll resolve the conflict, sorry I didn't review this earlier will fit this into the next Chart release. Thank you !

**Comment by wongma7** [comment]
/retest

```

cluster "test-cluster-3231.k8s.local" already exists; use 'kops update cluster' to apply changes
2020/12/22 19:16:05 Up failed: exit status 1 
```
coincidence? I guess 4 digit random number is not good enough.

**Comment by innovia** [comment]
@wiesa1 can we get this merged I really need that and don't want to fork the chart

**Comment by innovia** [comment]
> @wiesa1 can we get this merged I really need that and don't want to fork the chart

sorry nevermind its in deamonset already
      `priorityClassName: system-node-critical`

**Comment by wongma7** [comment]
/close

this has since been merged in a different form ! now you can pass namespace arg to helm to achieve same thing

**Pull request closed without merging**
