### PR TITLE
Add Pod Identity documentation in README

### PR DESCRIPTION
**Pull request by arnavgup1**
**Is this a bug fix or adding new feature?**
Feature

**What is this PR about? / Why do we need it?**
Adds documentation for the Pod Identity feature used for customers that want to authenticate with the pod identity agent that is available through EKS Add-ons. 

PR for the pod identity change: https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1254

### CODE REVIEW

**Review by seanzatzdev-amazon — APPROVED** [review]

**Comment by kkopachev** [comment]
I have a question about the language added by this PR. 
It seems that adding `AmazonEFSCSIDriverPolicy` policy to the cluster's node group's IAM role is essentially the same as third method using instance profile policy:
If my node has  `AmazonEFSCSIDriverPolicy` on it, then any pod on that node can use it, regardless of EKS Pod Identity presence. 
Am I missing something here?

**Comment by leondkr** [comment]
Hi @kkopachev 

You can check my [PR#1422](https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1422/files) here for further explanation of using EKS Pod Identities feature with EFS CSI.

Basically, it is only required to be added with the IAM role associated with EFS CSI controller.

**Pull request merged**
