### PR TITLE
feat: add support for additional pod labels

### PR DESCRIPTION
**Pull request by jaygridley**
**Is this a bug fix or adding new feature?**
Feature

**What is this PR about? / Why do we need it?**
Extends Helm chart with additional Pod labels capability

**What testing is done?** 
Locally generated template from the Helm chart

### CODE REVIEW

**Comment by gadiener** [comment]
Hello @nckturner and @wongma7 can we please get a review here?

**Comment by sellers** [comment]
This change seems very straight forward and would help the thousands of users who are trying to do cost management and attribution for different aspects using labels.  Many of our cost and inventory reporting tools use labels to do aggregation and visibility and labels are the way we can do that with ease.  Thank you for creating this recommendation and it seems like the Helm way to do this for Pods.

**Comment by bharathiram** [comment]
Can we please get a review on this? This feature will be so helpful for us

**Comment by gadiener** [comment]
@nckturner, @wongma7 any chance you can look into that?

**Comment by guanchzhou** [comment]
Does anyone know hot to expedite this PR?

@jaygridley are you still working on this?

**Comment by jaygridley** [comment]
Work from this PR was already done in https://github.com/kubernetes-sigs/aws-efs-csi-driver/commit/3a87e1d001688bacebd872b982bd9496ca96c8d3 and

**Pull request closed without merging**
