### PR TITLE
add hostAliases to the helm chart to handle cross VPC mountpoint

### PR DESCRIPTION
**Pull request by jurgenweber**
**Is this a bug fix or adding new feature?**
New feature

**What is this PR about? / Why do we need it?**
 for cross VPC EFS, you need to poison or overwrite the DNS for the efs volume as per
 https://docs.aws.amazon.com/efs/latest/ug/efs-different-vpc.html#wt6-efs-utils-step3
 implementing the suggested solution found here:
 https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/240#issuecomment-676849346

**What testing is done?** 
helm template and added into my cluster.

### CODE REVIEW

**Comment by jurgenweber** [comment]
any word?

**Comment by jurgenweber** [comment]
i'd love to get this over the line, Thanks

**Comment by wongma7** [comment]
/lgtm
/approve

 read the doc and issue, maks sense to me!! thanks.

**Pull request merged**
