### PR TITLE
Feat/#436

### PR DESCRIPTION
**Pull request by jurgenweber**
**Is this a bug fix or adding new feature?** bug/fix

**What is this PR about? / Why do we need it?**

https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/436

**What testing is done?** 
helm template

### CODE REVIEW

**Comment by jurgenweber** [comment]
well, thats on you. You took too long

**Comment by BenjaminFarley** [comment]
Hi, is there any chance that we can get this rebased and reviewed?

**Comment by jurgen-weber-deltatre** [comment]
I ended up in rebase hell, I suggest we close this and go again.

**Pull request closed without merging**
