### PR TITLE
Update to k8s v1.18.10

### PR DESCRIPTION
**Pull request by chrishenzie**
**Is this a bug fix or adding new feature?**
New feature.

**What is this PR about? / Why do we need it?**
This PR updates the version of k8s dependencies to v1.18.10.

The reason I'd like to update to this version is because versions >= v1.18 [include support for `AddAfterEach()` in the E2E test framework](https://github.com/kubernetes/kubernetes/commit/ea913f38ead3fb97c1e9086f65b01c680e078ed8), which ensures all resources (especially non-namespaced resources) are cleaned up if an E2E test is interrupted. I have tried to do something similar with `ginkgo.AfterEach()` but couldn't get the callback to execute.

**What did you run to produce this commit?**
Use this script to update to v1.18.10:
```sh
hack/update-gomod v1.18.10
```

Manually updated the following `require`ments in `go.mod`:
```diff
# Updated the kubernetes requirement because the script did not affect it.
-       k8s.io/kubernetes v1.17.6
+       k8s.io/kubernetes v1.18.10
```

Manually updated the following `replace`ments in `go.mod`:
```diff
# Because these were bumped to a release candidate version, moving them back for consistency
-       k8s.io/apimachinery => k8s.io/apimachinery v0.18.11-rc.0
+       k8s.io/apimachinery => k8s.io/apimachinery v0.18.10
-       k8s.io/code-generator => k8s.io/code-generator v0.18.11-rc.0
+       k8s.io/code-generator => k8s.io/code-generator v0.18.10
-       k8s.io/cri-api => k8s.io/cri-api v0.18.11-rc.0
+       k8s.io/cri-api => k8s.io/cri-api v0.18.10

# This was not bumped, bumping for consistency.
-       k8s.io/node-api => k8s.io/node-api v0.17.6
+       k8s.io/node-api => k8s.io/node-api v0.18.10
```

Updated generated mocks:
```sh
hack/update-gomock
```

Wipe out vendor/ and `go.sum` and start fresh just to be sure. Verify the results:
```sh
rm -rf vendor/ go.sum

go mod vendor

go mod tidy

go mod verify
all modules verified
```

**What things needed to be changed?**
Method signatures for k8s APIs in E2E tests now include context and options.

**What testing is done?**
Unit tests and build targets succeed.

Additionally, built and deployed this EFS driver version in a cluster and was able to successfully use an EFS PersistentVolume.

@msau42

### CODE REVIEW

**Comment by wongma7** [comment]
/lgtm
/approve
thank you

**Comment by chrishenzie** [comment]
Small merge conflict in E2E test with change for efs-driver-namespace flag, force pushed an update

**Pull request merged**
