### PR TITLE
Move to new s3 bucket

### PR DESCRIPTION
**Pull request by dims**
New account means new bucket :)

related to : https://github.com/kubernetes/k8s.io/issues/5194

pulled in fix from @torredil here https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1138

### CODE REVIEW

**Comment by dims** [comment]
made some progress, now stuck with `Access Denied. Please ensure you have the right AWS permissions: Access denied` please see:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_aws-efs-csi-driver/1137/pull-aws-efs-csi-driver-e2e/1702866666553085952/build-log.txt

docs point to `ClientRootAccess` https://docs.aws.amazon.com/efs/latest/ug/efs-access-points.html#efs-access-poiont-create - where do we need to specify that?

**Review by torredil — APPROVED** [review]
/approve

**Pull request merged**
