### PR TITLE
add updateStrategy

### PR DESCRIPTION
**Pull request by nalbam**
**Is this a bug fix or adding new feature?**

Feature

**What is this PR about? / Why do we need it?**

Added updateStrategy to controller and deamonset.
When deploying to a large number of nodes, the deployment speed can be faster.
Code referenced aws-ebs-csi-driver .

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/templates/controller.yaml#L10

**What testing is done?**

### CODE REVIEW

**Comment by Legion2** [comment]
We need this for the daemon set, we have so many pods that we get timeouts on rollouts, because all pods are replaced sequentially.

**Comment by pierluigilenoci** [comment]
@nalbam any news about this?

**Comment by pierluigilenoci** [comment]
@nalbam why closed?

**Comment by 617m4rc** [comment]
What is required to get this reviewed and approved?

**Comment by pierluigilenoci** [comment]
@617m4rc this is now closed. 
You can try to make a new PR.

**Pull request closed without merging**
