### PR TITLE
Fast-forward to latest ebs hack/e2e scripts with eksctl support, k8s 1.20, etc.

### PR DESCRIPTION
**Pull request by wongma7**
**Is this a bug fix or adding new feature?**

**What is this PR about? / Why do we need it?**
I applied the latest version of scripts from https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/hack/e2e
```
git fetch ebs                                                                  
git diff HEAD:hack/e2e ebs/master:hack/e2e > /tmp/hack_e2e.diff                
git apply --reject --directory hack/e2e /tmp/hack_e2e.diff
git commit
```

**What testing is done?** 
scripts work in ebs repo, will let CI test if they continue to work in this one.

### CODE REVIEW

**Comment by nckturner** [comment]
So are the copied from the EBS repository with slight modifications?  Don't we use submodules to avoid copying scripts?  (Should we start moving some shared scripts, like the eksctl, to https://github.com/kubernetes-sigs/provider-aws-test-infra?)

**Comment by wongma7** [comment]
@nckturner there are no modifications, see the commands i  did in the pr test. submodules doesn't work well for copying a subdirectory, that's why i use read-tree and the commands i did.

**Comment by nckturner** [comment]
Ok, Not sure exactly what you mean, I think we can probably solve this by moving anything that is the same to the test-infra respository but I'm not going to block on that.

**Pull request merged**
