### PR TITLE
Revert "EFS-CSI pod impersonation implementation"

### PR DESCRIPTION
**Pull request by wongma7**
Reverts kubernetes-sigs/aws-efs-csi-driver#710

### CODE REVIEW

**Comment by adammw** [comment]
Is there any more information on the reason for the revert?

**Comment by andrecastro** [comment]
Why this was reverted?

**Comment by dims** [comment]
@adammw @andrecastro can you please share some context on why the sudden interest in a revert after 2-ish years?

**Comment by andrecastro** [comment]
@dims I manage a multi-tenant platform based on k8s, meaning I have applications of different teams sharing the same cluster. I would like to whitelist the access to the applications using the EFS resource policy, restricting the access only to the roles associated to the pods (IRSA) that need access.

Right now I'm doing it via templates and naming patterns that we have in our platform, but I think this feature would be a valid option thinking about security concerns.

The [secrets-store-csi-driver-provider-aws](https://github.com/aws/secrets-store-csi-driver-provider-aws) have something similar. I can create secrets on AWS Secrets Manager and restrict the access to the pods. The provider kind of impersonate the pod mounting the secret, using its permissions.

**Comment by dims** [comment]
@andrecastro thanks for sharing! please open a new issue and point it back to the discussion here (and cut-n-paste the info here). it's just that folks don't really pay attention to old closed PRs and better visibility as a fresh request.

**Comment by adammw** [comment]
#1439 was opened back in August

**Pull request merged**
