### PR TITLE
Refactor and extend node tests

### PR DESCRIPTION
**Pull request by 2uasimojo**
**Is this a bug fix or adding new feature?**

Neither; cleaning up and extending tests.

**What is this PR about? / Why do we need it?**

Make tests more maintainable. Make tests more thorough.

**What testing is done?** 

Extended testing of Node{P|Unp}upblishVolume to
validate the error codes and message strings. Not that it's super
important that these strings are spelled exactly right; more to make
sure we're erroring from the exact places we are expecting for each test
case.

### CODE REVIEW

**Comment by 2uasimojo** [comment]
Between this and #189, one will need a rebase when the other merges.

**Comment by wongma7** [comment]
/hold
to give you time to rebase this on #189

**Comment by 2uasimojo** [comment]
> /hold
> to give you time to rebase this on #189

Done. Also fixed some test fails I somehow missed, and de-linted. Thanks @wongma7.

**Comment by 2uasimojo** [comment]
Wow. I think the coverage is "reduced" because I trimmed one line out of node.go, thereby reducing both the numerator and denominator in the equation by one. That seems like something the coverage tool ought to take into account.

For now, I'll just blow that back into two lines :man_shrugging:

**Comment by 2uasimojo** [comment]
Oh, is the coverage job nonblocking?

**Comment by wongma7** [comment]
Yeah it's non blocking, I guess we don't have to worry about it.

/lgtm
/hold cancel

**Pull request merged**
