### PR TITLE
Add support for on-premise Kubernetes environment

### PR DESCRIPTION
**Pull request by davidshtian**
**Is this a bug fix or adding new feature?**
Yes, this is add feature for supporting on-premise Kubernetes environment to deploy Amazon EFS CSI Driver, and this is related to [issue 468](https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/468).

**What is this PR about? / Why do we need it?**
As on-premise Kubernetes users also would like to leverage Amazon EFS service for shared file system, while currently there are several issues when deploying to on-premise environment, like EC2 metadata service dependency.

**What testing is done?** 
I've tested using actual on-premise Kubernetes environment.

### CODE REVIEW

**Comment by wongma7** [comment]
/ok-to-test

Over at https://github.com/kubernetes-sigs/aws-ebs-csi-driver we have been working on decoupling driver from instance metadata as well. And I was planning to port the solution here. The solution over there is to check, in order:
1. EC2 instance metadata
2. Kubernetes API (fall back to this because the node object has instance id, region, zone in spec.providerID)

Do your Nodes have spec.providerID set? If so, the solution could work here too.

Still, there is value in adding environment variable overrides in case spec.providerID is not set or kubernetes API access is blocked from CSI node pods.

The order could be something like:

1. Environment variable override (this PR). 
2. ECS/fargate instance metadata
3. EC2 instance metadata
4. Kubernetes API (the node object has instance id, region, zone in spec.providerID)

Let me know what you think.

**Comment by davidshtian** [comment]
> /ok-to-test
> 
> Over at https://github.com/kubernetes-sigs/aws-ebs-csi-driver we have been working on decoupling driver from instance metadata as well. And I was planning to port the solution here. The solution over there is to check, in order:
> 
> 1. EC2 instance metadata
> 2. Kubernetes API (fall back to this because the node object has instance id, region, zone in spec.providerID)
> 
> Do your Nodes have spec.providerID set? If so, the solution could work here too.
> 
> Still, there is value in adding environment variable overrides in case spec.providerID is not set or kubernetes API access is blocked from CSI node pods.
> 
> The order could be something like:
> 
> 1. Environment variable override (this PR).
> 2. ECS/fargate instance metadata
> 3. EC2 instance metadata
> 4. Kubernetes API (the node object has instance id, region, zone in spec.providerID)
> 
> Let me know what you think.

Hi~ The check order looks great! I've checked that there is no "spec.providerID" in on premise environment, it seems to be set by Cloud Controller Manager. Thanks~

**Comment by CNLHC** [comment]
> /ok-to-test
> 
> Over at https://github.com/kubernetes-sigs/aws-ebs-csi-driver we have been working on decoupling driver from instance metadata as well. And I was planning to port the solution here. The solution over there is to check, in order:
> 
> 1. EC2 instance metadata
> 2. Kubernetes API (fall back to this because the node object has instance id, region, zone in spec.providerID)
> 
> Do your Nodes have spec.providerID set? If so, the solution could work here too.
> 
> Still, there is value in adding environment variable overrides in case spec.providerID is not set or kubernetes API access is blocked from CSI node pods.
> 
> The order could be something like:
> 
> 1. Environment variable override (this PR).
> 2. ECS/fargate instance metadata
> 3. EC2 instance metadata
> 4. Kubernetes API (the node object has instance id, region, zone in spec.providerID)
> 
> Let me know what you think.

Hello @wongma7 
It seems that this feature does not gain some progress yet.  Are you still working on this feature? If you are too busy to work on this I am glad to sign the CLA and develop this.

**Comment by jonathanrainer** [comment]
> > /ok-to-test
> 
> > 
> 
> > Over at https://github.com/kubernetes-sigs/aws-ebs-csi-driver we have been working on decoupling driver from instance metadata as well. And I was planning to port the solution here. The solution over there is to check, in order:
> 
> > 
> 
> > 1. EC2 instance metadata
> 
> > 2. Kubernetes API (fall back to this because the node object has instance id, region, zone in spec.providerID)
> 
> > 
> 
> > Do your Nodes have spec.providerID set? If so, the solution could work here too.
> 
> > 
> 
> > Still, there is value in adding environment variable overrides in case spec.providerID is not set or kubernetes API access is blocked from CSI node pods.
> 
> > 
> 
> > The order could be something like:
> 
> > 
> 
> > 1. Environment variable override (this PR).
> 
> > 2. ECS/fargate instance metadata
> 
> > 3. EC2 instance metadata
> 
> > 4. Kubernetes API (the node object has instance id, region, zone in spec.providerID)
> 
> > 
> 
> > Let me know what you think.
> 
> 
> 
> Hello @wongma7 
> 
> It seems that this feature does not gain some progress yet.  Are you still working on this feature? If you are too busy to work on this I am glad to sign the CLA and develop this.

Hi, I have a PR open for this in #681. Would very much appreciate a review :)

**Pull request closed without merging**
