### PR TITLE
Don't exit script prematurely if test fails

### PR DESCRIPTION
**Pull request by wongma7**
**Is this a bug fix or adding new feature?**

**What is this PR about? / Why do we need it?** copy of https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/373 onto release-1.2

**What testing is done?**

### CODE REVIEW

**Comment by wongma7** [comment]
ref flaky tests, need this for debugging : https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/374

**Review by nckturner — APPROVED** [review]

**Pull request merged**
