### PR TITLE
Cherry-pick for new release v1.7.6

### PR DESCRIPTION
**Pull request by mjsoyeon**
**Is this a bug fix or adding new feature?**

**What is this PR about? / Why do we need it?**
Cherry-pick for new release v1.7.6

**What testing is done?**

### CODE REVIEW

**Review by torredil — APPROVED** [review]
/lgtm
/approve

**Comment by Ashley-wenyizha** [comment]
Could you point to me where is the commit to `Update efs-csi-driver to use efs-utils latest release v1.35.2` as updated in pre-release PR? thanks

**Comment by mjsoyeon** [comment]
> Could you point to me where is the commit to `Update efs-csi-driver to use efs-utils latest release v1.35.2` as updated in pre-release PR? thanks

https://github.com/aws/efs-utils/releases/tag/v1.35.2

**Pull request merged**
