### PR TITLE
Migrate to use aws-sdk-go-v2

### PR DESCRIPTION
**Pull request by avanish23**
Is this a bug fix or adding new feature?
This PR migrates to aws-sdk-go-v2 
Context: https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-go-v1-on-july-31-2025/
Migration guide: https://aws.github.io/aws-sdk-go-v2/docs/migrating/

Basically maintenance mode on July 31, 2024 and reach end-of-support on July 31, 2025. The SDK will not
receive API updates for new or existing services, or be updated to support new regions.

Side note: Most of the changes are present in the /vendors directory as the aws-sdk-go-v2 files have gotten added, which don't need a really need a review, so the review process can be limited to 10 files

PR for issue https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/1421

What is this PR about? / Why do we need it?

What testing is done?
make test has passed succesfully

### CODE REVIEW

**Comment by mskanth972** [comment]
Will review it by tomorrow

**Comment by avanish23** [comment]
@k8s-ci-robot check cla

**Comment by mskanth972** [comment]
@avanish23, can you try to get the `easycla` issue resolved, so that I can approve?

**Pull request merged**
