### PR TITLE
Update readme for release branch v1.4

### PR DESCRIPTION
**Pull request by Ashley-wenyizha**
**Is this a bug fix or adding new feature?**
Update readme file
**What is this PR about? / Why do we need it?**
Update readme for release branch v1.4
**What testing is done?**

### CODE REVIEW

**Comment by wongma7** [comment]
is this meant for release-1.4 branch

**Comment by Ashley-wenyizha** [comment]
> is this meant for release-1.4 branch

thanks for taking a look!!

yes this is meant for 1.4 branch

**Comment by wongma7** [comment]
/lgtm
/approve
/hold
this change needs to go into release-1.4 branch https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/724/files#diff-c3f1629e788cf3c7ab0c0cb4bbb81632e03e49ea6daccf6a58e6887c739f3dfe before we start directing people to do release-1.4 kustomize install

**Comment by Ashley-wenyizha** [comment]
remove /hold

**Pull request closed without merging**
