### PR TITLE
Add logLevel to helm

### PR DESCRIPTION
**Pull request by tatsuya-ogawa**
**Is this a bug fix or adding new feature?**
Add logLevel variable to helm chart.

**What is this PR about? / Why do we need it?**
Because it is necessary to specify logLevel when alerting from the log collected from log collector like fluent-bit.

### CODE REVIEW

**Comment by tatsuya-ogawa** [comment]
I signed it

**Comment by tatsuya-ogawa** [comment]
I signed it

**Comment by tatsuya-ogawa** [comment]
I signed it.

**Comment by wongma7** [comment]
/lgtm
/approve

I'm sorry I didn't see this earlier, I'll try to resolve conflcts myself.

**Pull request merged**
