### PR TITLE
[release-1.3] cherry-pick: Only reap zombie stunnel processes

### PR DESCRIPTION
**Pull request by chrishenzie**
**Is this a bug fix or adding new feature?**
Fixing a bug.

**What is this PR about? / Why do we need it?**
This is a cherry-pick of https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/514, which fixes an issue where mounts occasionally fail with:
```
mount_linux.go:150] Mount failed: waitid: no child processes
```

**What testing is done?**
Currently smoke-testing this in an AWS cluster and running the EFS E2E test suite repeatedly. For context, this issue has been cropping up occasionally and causing test-flakiness. Will post back with the results.

/assign @wongma7 
/assign @kbasv

### CODE REVIEW

**Comment by wongma7** [comment]
/lgtm
/hold

feel free to cancel hold when testing is done if testing shows that this fixes the issue. then we can make a release.

@kbasv and I were going to hold this patch until 1.4.0 as we couldn't reproduce the issue and verify this was actually a bug fix but if your testing shows otherwise we should make a 1.3.x fix.

**Comment by chrishenzie** [comment]
@wongma7 Thank you! For clarification, we have some E2E tests that run this test suite periodically and have encountered some test flakes due to timeouts. When I inspect the logs I see this line about no child processes. I was able to repro locally by re-running the E2E test-suite repeatedly until it exited with code != 0.

**Comment by chrishenzie** [comment]
@wongma7 The test ran successfully 34 times over a 17 hour span without any failures. Removing the hold.

/hold cancel

**Pull request merged**
