### PR TITLE
Add e2e test for dynamic provisioning

### PR DESCRIPTION
**Pull request by seanzatzdev-amazon**
**Is this a bug fix or adding new feature?**
Adds new e2e test

**What is this PR about? / Why do we need it?**
This PR adds an e2e test for dynamic provisioning. It simply performs dynamic provisioning, then writes to and reads from the persistent volume to ensure that everything works correctly. 

This is important as currently in the EFS-CSI test suite we do not have e2e tests which cover Dynamic Provisioning, and thus we do not have e2e test coverage for EFS-specific CSI Driver features such as "ensureUniqueDirectory". Adding this test allows us more coverage, and will additionally allow us to more easily add further coverage for additional features in the future.

**What testing is done?** 
Test passes on local.

### CODE REVIEW

**Comment by mskanth972** [comment]
I think we already have dynamic provisioning e2e test cases [link](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/test/e2e/e2e.go#L112). And also we have a test cases to check the read/write functionality [link](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/test/e2e/e2e.go#L276). Should we need this again?

**Comment by seanzatzdev-amazon** [comment]
> link

Hey Shashi, what you say is true. Though the dynamic provisioning definition you linked is only for use by the kubernetes e2e tests which as I understand do not test EFS-specific features (such as storage class features like subpath pattern, reusingAccessPoints, etc). The reading/writing is also tested currently but for static provisioning.

Combining both of these aspects into a new EFS-specific e2e test will allow us to add more robustness in the tests later on.

**Comment by mskanth972** [comment]
> > I think we already have dynamic provisioning e2e test cases [link](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/test/e2e/e2e.go#L112). And also we have a test cases to check the read/write functionality [link](https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/test/e2e/e2e.go#L276). Should we need this again?
> 
> Hey Shashi, what you say is true. Though the dynamic provisioning definition you linked is intended to be used by the kubernetes e2e tests which as I understand do not test EFS-specific features (such as storage class features like subpath pattern, reusingAccessPoints, etc). The reading/writing is also tested currently but for static provisioning.
> 
> Combining both of these aspects into a new EFS-specific e2e test will allow us to add more robustness in the tests later on.

Okay, it makes sense.

**Pull request merged**
