### PR TITLE
Add optional podDisruptionBudget to controller deployment

### PR DESCRIPTION
**Pull request by gdziwoki**
**Is this a bug fix or adding new feature?**
Feature

**What is this PR about? / Why do we need it?**
Add optional podDisruptionBudget to controller deployment

**What testing is done?** 
Template locally podDistruptionBudget with and without values

### CODE REVIEW

**Comment by gdziwoki** [comment]
I signed it

**Comment by artificial-aidan** [comment]
@gdziwoki

**Comment by qdupuy** [comment]
/reopen

🖖 @gdziwoki please update your commit

**Comment by BojanZelic** [comment]
any chance of getting this re-opened? 

The PDB would be useful for allowing the autoscaler to scale down; currently running into this without it:

```
Fast evaluation: node ip-xx-xx-xx-xx.us-west-2.compute.internal cannot be removed: non-daemonset, non-mirrored, non-pdb-assigned kube-system pod present: efs-csi-controller-6746997d6f-xlr5z
```

**Comment by starlightromero** [comment]
Please reopen this MR. The PDB is now somewhat of a standard for pods

**Pull request closed without merging**
