### PR TITLE
CHANGELOG UPDATED

### PR DESCRIPTION
**Pull request by mskanth972**
**Is this a bug fix or adding new feature?**

**What is this PR about? / Why do we need it?**

**What testing is done?**

### CODE REVIEW

**Comment by tjdett** [comment]
This doesn't mention the removal of pod IAM impersonation (#710) by #776/#777?

Was that feature intentionally removed?

**Comment by Ashley-wenyizha** [comment]
@tjdett Hi Tim, because of lacking AWS EKS security review on the feature, it's rolled back and security review is in progress, you can follow up with @wongma7 for updates.

**Pull request merged**
