### PR TITLE
Move chart to charts directory and add workflow to publish new chart versions

### PR DESCRIPTION
**Pull request by wongma7**
**Is this a bug fix or adding new feature?** fix for broken/outdated helm charts. automatic release.

**What is this PR about? / Why do we need it?** This is basically a copy of @krmichel's contribution to EBS which has been working nicely: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/624. We need it because manual release of the helm chart ought to be automated.

~~TODO: I have to unprotect the gh-pages branch, same as I did for EBS: https://github.com/kubernetes/test-infra/pull/20323~~

**What testing is done?** tested in my fork by releasing a dummy 0.2.0 chart:

https://github.com/wongma7/aws-efs-csi-driver/blob/gh-pages/index.yaml
https://github.com/wongma7/aws-efs-csi-driver/releases/tag/helm-chart-aws-efs-csi-driver-0.2.0

### CODE REVIEW

**Comment by ayberk** [comment]
Are we going to have an extra release for the chart similar to the ebs driver?

**Comment by krmichel** [comment]
> Are we going to have an extra release for the chart similar to the ebs driver?

If I understand the question correctly the answer is yes.  There will be releases that are generated when the chart version changes.  These releases will be what the chart repo links to for helm to download the charts from.  If files in the charts subdirectory are changed without updating the chart version in the Chart.yaml the action will fail.

**Comment by krmichel** [comment]
@wongma7 This was on my list of things to get to but you beat me to it, thanks.  I don't know if it is a concern, but the information in the current chart index is incorrect currently.  If you want me to fix it let me know and I can make a PR (which would need merged before this one).  Before this is merged you will also want to update the version in the Chart.yaml.

**Comment by wongma7** [comment]
>  I don't know if it is a concern, but the information in the current chart index is incorrect currently.  If you want me to fix it let me know and I can make a PR (which would need merged before this one).

@krmichel I was going to test whether the chart-releaser action would automagically reconcile the Chart.yaml to the correct state but that's optimistic, the fix to index should probably happen first as you say. I will try to prep a PR and will ping you for review, technically we can't merge any PRs/fixes to the gh-pages branch until after https://github.com/kubernetes/test-infra/pull/20323 anyway. (Previous index fixes have been admins pushing to the branch directly, turns out I don't have that power in this repo )
I'll rebase and bump chart version soon

**Comment by wongma7** [comment]
Rebased and ready for review. I reset chart version to 0.1.0 to match what is currently in index.yaml, otherwise merging this will trigger another duplicate release chart version 0.3.0

**Comment by wongma7** [comment]
test failures seem legit, will check and maybe repro locally.

**Comment by krmichel** [comment]
In general it looks good to me.  I am not 100% sure if the action will succeed since the index already has a 0.1.0 version of the chart in it but doesn't have a release that matches the naming convention.  I guess we will find out.

**Comment by wongma7** [comment]
/hold

Let me test what happens in my fork.

I hope it does nothing, I don't want it to tag HEAD as helm-chart-0.1.0 because that would be inaccurate.
Basically I want to treat 0.1.0 as the last working manual release before we switch to this, but we can't switch yet until https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/296 merges

**Comment by wongma7** [comment]
In my fork, upon merging this to master, it made a new release helm-chart-aws-efs-csi-driver-0.1.0, which I don't think is right. https://github.com/wongma7/aws-efs-csi-driver/releases

So what I am going to do is hold this PR, get https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/296 merged first, and then merge this but with chart verison set to 1.0.0 so we can start the charts with a clean slate given the messy state with 0.2.0 and 0.3.0 half-existing (they existed at some points in Chart.yaml but were not correctly released to index.yaml). The appVersion/driver version is going to still be 1.0.0, the difference from chart 0.1.0 and 1.0.0 will be all the various helm chart contributions from the last few months.

**Comment by wongma7** [comment]
Since the release action didn't actually update index.yaml, it should be fine to merge this, I will simply delete the GitHub release it generates.

Rebasing now

**Comment by wongma7** [comment]
/hold cancel

Will be fine to merge now that helm charts 1.0.0 and 1.1.0 were manually created

sorry for all the noise and back and forth!!

**Pull request merged**
