### PR TITLE
Tags configurations dynamically provisioning

### PR DESCRIPTION
**Pull request by omerap12**
**Is this a bug fix or adding new feature?**
Add Tags Configurations In dynamically Provisioning Access Points. Added tests

**What is this PR about? / Why do we need it?**
#1346 

**What testing is done?** 
Manually tested by using the following manifest:

```bash
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0d4bbee0eb9759244
  directoryPerms: "700"
  pvcTags: "service_name=my_service,team=infra,environment=development"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: efs-example
spec:
  containers:
    - name: app
      image: centos
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo $(date -u) >> /example/out.txt; sleep 5; done"]
      volumeMounts:
        - name: persistent-storage
          mountPath: /example
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: efs-claim
```

Which created the following tags:
image

### CODE REVIEW

**Comment by omerap12** [comment]
Hey, can you please review? 
@Ashley-wenyizha 
@mskanth972

**Comment by genural** [comment]
Hey, any update?

**Comment by aymen-cherif** [comment]
Any updates please?

**Pull request closed without merging**
