### PR TITLE
changelog/readme/makefile udpate for v1.3.7 release

### PR DESCRIPTION
**Pull request by Ashley-wenyizha**
**Is this a bug fix or adding new feature?**
Release note of v1.3.7
**What is this PR about? / Why do we need it?**
changelog/readme/makefile udpate for v1.3.7 release
**What testing is done?**

### CODE REVIEW

**Comment by Cappuccinuo** [comment]
@Ashley-wenyizha There is [watchdog configuration change in efs-utils 1.32.1](https://github.com/aws/efs-utils/blob/master/dist/efs-utils.conf#L67-L70), do we need to update driver side https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/pkg/driver/efs_watch_dog.go as well?

**Comment by wongma7** [comment]
just waiting for
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/654
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/662
/retest

The efs-utils version is dictated at time the image is built, so if u pull 1.3.6 now it has 1.31.3, so I do not think it is necessary to pin efs-utils. Rather we can continue the current model where we just pull whatever happens to be newest at time the image is built, with some exceptions (e.g. when there was some bug in version Y and we deliberately pinned to older version X to rollback)

~ $ docker run --entrypoint sh -it amazon/aws-efs-csi-driver:v1.3.6
sh-4.2# yum info amazon-efs-utils
Loaded plugins: ovl, priorities
Repodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast
Installed Packages
Name        : amazon-efs-utils
Arch        : noarch
Version     : 1.31.3

**Pull request merged**
